title: Amzer - les associations
remote_theme: violaine-web/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  argol:
    output: true
  camaret-sur-mer:
    output: true
  crozon:
    output: true
  landevennec:
    output: true
  lanveoc:
    output: true
  le-faou:
    output: true
  pont-de-buis-les-quimerch:
    output: true
  roscanvel:
    output: true
  rosnoen:
    output: true
  telgruc-sur-mer:
    output: true
    

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
