title: Amzer - les associations
remote_theme: violaine-web/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  camaret:
    output: true
  lanveoc:
    output: true
    

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
